### ISSUE TITLE
Overflow menu misplaced in landscape mode in iOS 9

### ISSUE THREAD

**Issue by AmrKafina** [sudeepjaiswal/ASJOverflowButton#3]
When a device rotated to landscape mode, the menu isn't displayed properly. I believe the issue has something to do with the autoresizing masks: 

`- (UIViewAutoresizing)autoresizingMasks {`
`return UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;`
`}`

![simulator screen shot oct 14 2016 9 13 20 am](https://cloud.githubusercontent.com/assets/3764110/19377400/b5c25060-91ee-11e6-9500-37c8be075b38.png)

The issue seems to only appear on iPhone devices, not iPads. Apparently when the status bar is hidden (as is the case on iPhone devices in landscape), opening the menu makes the status bar appear again and causes the issue.

**Comment by sdpjswl** [comment]
You seem to be right, it seems related to the status bar hiding and showing. The menu is actually shown on a new `UIWindow`, I think that's where the status bar comes from. I'll look more into this issue.

**Comment by AmrKafina** [comment]
Yup, found [this](http://stackoverflow.com/questions/23151191/programatically-hiding-status-bar-when-adding-new-uiwindow) on stackoverflow, which fixed most of the issue, but you still have to add a check to keep the status bar from disappearing all the time (ie in portrait). Also have to edit the menu's height / frame to accommodate for the missing status bar.

**Comment by AmrKafina** [comment]
Turns our all you have to do is set a rootviewcontroller for the window (`_overflowWindow.rootViewController = [UIViewController new];`), and change `autoresizingMasks` to return `UIViewAutoresizingNone` (not sure if this screws up something else). 

There's still the issue of the menu's height when in a vertically compact environment / when no status bar is shown.

**Comment by sdpjswl** [comment]
Setting a dummy root view controller does the job; no longer the status bar shows-hides on rotation. I have set the root view controller and committed the change. Please take a look. I will keep trying on my end.

My observations:
1. Setting `UIViewAutoresizingNone` on the menu's `UIWindow` doesn't seem to make a difference.
2. The issue happens when menu is already open and rotation occurs. Then the menu size/position gets all screwed up. Do you have any suggestions? I tried to hide existing menu and show new one after rotation but it didn't work.
3. However, If menu is not showing and after rotation, I tap the show button, the menu shows normally like it does in portrait.
4. In whatever orientation the menu is shown, the height is not correct, it is slightly less than expected in landscape and slightly more in portrait. In portrait, the menu should end with Item 6's separator.

This is strange. The menu uses a `UITableView` to show the options. My calculation for the menu's height and the table view's content height are exactly the same.

**Comment by sdpjswl** [comment]
Issue related to transform applied to menu view. Fixed.
